version: "3.4"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=34252187
      - POSTGRES_DB=POSTGRESQL
    expose:
      - "5432"
    ports:
      - "5432:5432"
  githubwebhook:
    image: githubwebhook
    build: .
    environment:
      - dataSource.url=jdbc:postgresql://postgres:5432/postgres
      - dataSource.dataSourceClassName=org.postgresql.Driver
      - dataSource.user=postgres
      - dataSource.password=34252187
      - dataSource.databaseName=postgres
      - dataSource.portNumber=5432
      - dataSource.serverName=postgres
      - liquibase.change-log=classpath:db/liquibase-changelog.xml
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres